IceCreamProject/Controllers/Login1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IceCreamProject.Models;

namespace IceCreamProject.Controllers
{
    public class Login1Controller : Controller
    {
        private readonly OrdersContext _context;

        public Login1Controller(OrdersContext context)
        {
            _context = context;
        }

        // GET: Login1
        public async Task<IActionResult> Index()
        {
            return View(await _context.Login1.ToListAsync());
        }

        // GET: Login1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var login1 = await _context.Login1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (login1 == null)
            {
                return NotFound();
            }

            return View(login1);
        }

        // GET: Login1/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Login()
        { 
            return View();
        }
        public IActionResult TryLogin(string username,string password)
        {
            foreach (var item in _context.Login1)
            {
                if (item.UserName == username && item.Password == password)
                {
                    HelpStaticClass.IsAdmin = true;
                    return View("~/Views/Home/ManagerIndex.cshtml");
                }
            }
            return View("~/Views/Home/Index.cshtml");
        }

        // POST: Login1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UserName,Password,Mail")] Login1 login1)
        {
            if (ModelState.IsValid)
            {
                _context.Add(login1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(login1);
        }

        // GET: Login1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var login1 = await _context.Login1.FindAsync(id);
            if (login1 == null)
            {
                return NotFound();
            }
            return View(login1);
        }

        // POST: Login1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UserName,Password,Mail")] Login1 login1)
        {
            if (id != login1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(login1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Login1Exists(login1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(login1);
        }

        // GET: Login1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var login1 = await _context.Login1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (login1 == null)
            {
                return NotFound();
            }

            return View(login1);
        }

        // POST: Login1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var login1 = await _context.Login1.FindAsync(id);
            _context.Login1.Remove(login1);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Login1Exists(int id)
        {
            return _context.Login1.Any(e => e.Id == id);
        }
    }
}

IceCreamProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon">
  <link rel="stylesheet" id="wp-block-library-rtl-css" href="https://bcdn.foodbox.co.il/static//wp-includes/css/dist/block-library/style-rtl.min.css?ver=563bcb92105189068480bc23f45e9dc3" media="all">

  <title>Coldbergs</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha256-mLBIhmBvigTFWPSCtvdu6a76T+3Xyt+K571hupeFLg4=" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="~/css/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="~/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="~/css/responsive.css" rel="stylesheet" />

</head>
<body>
<header>
      <div class="container-fluid" style="background-color:purple;">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand " href="index.html"> The IceCream House</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link"asp-controller="Home" asp-action="index">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="about"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="IceCreamFlavors" asp-action="index">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Orders" asp-action="create">Order</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Login1" asp-action="Login">Login</a>
              </li>
              <form class="form-inline justify-content-center">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </form>
            </ul>
          </div>
        </nav>
      </div>

</header>
    
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


  <!-- jQery -->
  <script src="js/jquery-3.4.1.min.js"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <!-- bootstrap js -->
  <script src="js/bootstrap.js"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
  <!-- custom js -->
  <script src="js/custom.js"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IceCreamProject/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon">
  <link rel="stylesheet" id="wp-block-library-rtl-css" href="https://bcdn.foodbox.co.il/static//wp-includes/css/dist/block-library/style-rtl.min.css?ver=563bcb92105189068480bc23f45e9dc3" media="all">

  <title>Coldbergs</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha256-mLBIhmBvigTFWPSCtvdu6a76T+3Xyt+K571hupeFLg4=" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="~/css/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="~/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="~/css/responsive.css" rel="stylesheet" />

</head>
<body>
<header>
      <div class="container-fluid" style="background-color:purple;">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand " href="index.html"> The IceCream House</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item active">
                <a class="nav-link"asp-controller="Home" asp-action="ManagerIndex">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="IceCreamFlavors" asp-action="create">Add IceCream</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Orders" asp-action="create">Create Order</a>
              </li>
                            <li class="nav-item">
                <a class="nav-link" asp-controller="Orders" asp-action="indexAdmin">Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Login1" asp-action="Login">Login</a>
              </li>
              <form class="form-inline justify-content-center">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </form>
            </ul>
          </div>
        </nav>
      </div>

</header>
    
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


  <!-- jQery -->
  <script src="js/jquery-3.4.1.min.js"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <!-- bootstrap js -->
  <script src="js/bootstrap.js"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
  <!-- custom js -->
  <script src="js/custom.js"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>